version: '3.5'

services:
  busca-endereco-viacep-app:
    build:
      context: '.'
    container_name: busca-endereco-viacep-app
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - "busca-endereco-viacep-db"
      - "busca-endereco-viacep-mail"
    networks:
      - app

  busca-endereco-viacep-db:
    image: mysql:8
    tty: true
    container_name: busca-endereco-viacep-db
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - DB_CONNECTION=mysql
      - DB_HOST=busca-endereco-viacep-db
      - DB_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - app

  busca-endereco-viacep-mail:
    image: mailhog/mailhog:latest
    container_name: busca-endereco-viacep-mail
    ports:
      - "8125:8025"
      - "2525:1025"
    environment:
      - MT_USER=busca-endereco-viacep
      - MT_PASSWD=busca-endereco-viacep
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001'
    networks:
      - app
    
  busca-endereco-viacep-redis:
    image: redis:latest
    container_name: busca-endereco-viacep-redis
    ports:
      - 6379:6379
    networks:
      - app
networks:
  app:
    driver: bridge
